use DB_WEB_TEST
go

CREATE TABLE User1 (
    IDUser INT PRIMARY KEY,
    Name NVARCHAR(50) NOT NULL,
	PassWord NVARCHAR(10) NOT NULL,
    SEX NVARCHAR(10) NOT NULL,
    Achievement INT NOT NULL,
    TotalScore INT NOT NULL
);
go
CREATE TABLE EXAM (
    IDEXAM INT PRIMARY KEY,
    IDPart1 INT NOT NULL,
    IDPart2 INT NOT NULL,
    IDPart3 INT NOT NULL,
    IDPart4 INT NOT NULL,
    IDPart5 INT NOT NULL,
    IDPart6 INT NOT NULL,
    IDPart7 INT NOT NULL
);
go

CREATE TABLE Thi_EXAM (
    IDUser INT,
    IDEXAM INT,
    FOREIGN KEY (IDUser) REFERENCES User1(IDUser),
    FOREIGN KEY (IDEXAM) REFERENCES EXAM(IDEXAM)
);
go

CREATE TABLE part1 (
	IDPart1 int primary key,
    pictures TEXT  NOT NULL,
    audio TEXT NOT NULL,
	PointPart1 INT NOT NULL
);
go

CREATE TABLE part2 (
	IDPart2 int primary key,
    audio TEXT NOT NULL,
    questions TEXT NOT NULL,
	PointPart2 INT NOT NULL
);
go

CREATE TABLE part3 (
	IDPart3 int primary key,
    audio TEXT NOT NULL,
    questions TEXT NOT NULL,
    pictures TEXT NOT NULL,
	PointPart3 INT NOT NULL
);
go

CREATE TABLE part4 (
	IDPart4 int primary key,
    audio TEXT NOT NULL,
    questions TEXT NOT NULL,
    pictures TEXT NOT NULL,
	PointPart4 INT NOT NULL
);
go

CREATE TABLE part5 (
	IDPart5 int primary key,
    questions TEXT NOT NULL,
	PointPart5 INT NOT NULL
);
go

CREATE TABLE part6 (
	IDPart6 int primary key,
    questions TEXT NOT NULL,
	pictures TEXT NOT NULL,
	PointPart6 INT NOT NULL

);
go

CREATE TABLE part7 (
	IDPart7 int primary key,
    questions TEXT NOT NULL,
	pictures TEXT NOT NULL,
	PointPart7 INT NOT NULL
);
go

CREATE TABLE QL_EXAM (
    IDPart1 INT,
	IDPart2 INT,
	IDPart3 INT,
	IDPart4 INT,
	IDPart5 INT,
	IDPart6 INT,
	IDPart7 INT,
    IDEXAM INT,
    FOREIGN KEY (IDPart1) REFERENCES part1(IDPart1),
    FOREIGN KEY (IDEXAM) REFERENCES EXAM(IDEXAM),
	FOREIGN KEY (IDPart2) REFERENCES part2(IDPart2),
	FOREIGN KEY (IDPart3) REFERENCES part3(IDPart3),
	FOREIGN KEY (IDPart4) REFERENCES part4(IDPart4),
	FOREIGN KEY (IDPart5) REFERENCES part5(IDPart5),
	FOREIGN KEY (IDPart6) REFERENCES part6(IDPart6),
	FOREIGN KEY (IDPart7) REFERENCES part7(IDPart7)
);
go

CREATE TABLE AUDIO (
	IDAudio INT PRIMARY KEY,
	LinkAudio TEXT NOT NULL
);
go

CREATE TABLE PICTURE (
	IDPicture INT PRIMARY KEY,
	LinkPicture TEXT NOT NULL
);
go

CREATE TABLE QUESTION (
	IDPQUESTION INT PRIMARY KEY,
	LinkQUESTION TEXT NOT NULL,
	A TEXT NOT NULL,
	B TEXT NOT NULL,
	C TEXT NOT NULL,
	D TEXT NOT NULL
);
go

CREATE TABLE QL_part1 (
	IDPart1 INT,
	IDPicture INT,
	IDAudio INT,
	FOREIGN KEY (IDPart1) REFERENCES part1(IDPart1),
	FOREIGN KEY (IDPicture) REFERENCES PICTURE(IDPicture),
	FOREIGN KEY (IDAudio) REFERENCES AUDIO(IDAudio),
);
go

CREATE TABLE QL_part2 (
	IDPart2 int,
	IDPQUESTION INT,
	IDAudio INT,
	FOREIGN KEY (IDAudio) REFERENCES AUDIO(IDAudio),
	FOREIGN KEY (IDPart2) REFERENCES part2(IDPart2),
	FOREIGN KEY (IDPQUESTION) REFERENCES QUESTION(IDPQUESTION)
);
go

CREATE TABLE QL_part3 (
	IDPart3 int,
	IDPQUESTION INT,
	IDAudio INT,
	FOREIGN KEY (IDAudio) REFERENCES AUDIO(IDAudio),
	FOREIGN KEY (IDPart3) REFERENCES part3(IDPart3),
	FOREIGN KEY (IDPQUESTION) REFERENCES QUESTION(IDPQUESTION)
);
go

CREATE TABLE QL_part4 (
	IDPart4 INT ,
	IDAudio INT,
	IDPicture INT,
	IDPQUESTION INT,
	FOREIGN KEY (IDPart4) REFERENCES part4(IDPart4),
	FOREIGN KEY (IDAudio) REFERENCES AUDIO(IDAudio),
	FOREIGN KEY (IDPQUESTION) REFERENCES QUESTION(IDPQUESTION),
	FOREIGN KEY (IDPicture) REFERENCES PICTURE(IDPicture)
);
go

CREATE TABLE QL_part5 (
	IDPart5 INT ,
	IDPQUESTION INT,
	FOREIGN KEY (IDPart5) REFERENCES part5(IDPart5),
	FOREIGN KEY (IDPQUESTION) REFERENCES QUESTION(IDPQUESTION)
);
go

CREATE TABLE QL_part6 (
	IDPart6 INT,
	IDPicture INT,
	IDPQUESTION INT,
	FOREIGN KEY (IDPart6) REFERENCES part6(IDPart6),
	FOREIGN KEY (IDPQUESTION) REFERENCES QUESTION(IDPQUESTION),
	FOREIGN KEY (IDPicture) REFERENCES PICTURE(IDPicture)
);
go

CREATE TABLE QL_part7 (
	IDPart7 INT,
	IDPicture INT,
	IDPQUESTION INT,
	FOREIGN KEY (IDPart7) REFERENCES part7(IDPart7),
	FOREIGN KEY (IDPQUESTION) REFERENCES QUESTION(IDPQUESTION),
	FOREIGN KEY (IDPicture) REFERENCES PICTURE(IDPicture)
);
go

CREATE TABLE QL_DIEM (
	IDUser INT,
	IDEXAM INT,
	PointPart1 INT,
	PointPart2 INT,
	PointPart3 INT,
	PointPart4 INT,
	PointPart5 INT,
	PointPart6 INT,
	PointPart7 INT,
	TotalScore INT,
	FOREIGN KEY (IDUser) REFERENCES User1(IDUser),
	FOREIGN KEY (IDEXAM) REFERENCES EXAM(IDEXAM)
)
