use DB_WEB_ENGLISH
go

CREATE TABLE User1 (
    IDUser INT PRIMARY KEY,
    Name NVARCHAR(50) NOT NULL,
	PassWord NVARCHAR(10) NOT NULL,
    SEX NVARCHAR(10) NOT NULL,
    Achievement INT NOT NULL,
    TotalScore INT NOT NULL
);
go

CREATE TABLE Thi_EXAM (
    IDUser INT,
    IDEXAM INT,
	Socore INT,
    FOREIGN KEY (IDUser) REFERENCES User1(IDUser),
    FOREIGN KEY (IDEXAM) REFERENCES QL_EXAM(IDEXAM)
);
go

CREATE TABLE Part1 (
	IDPart1 int primary key,
	PointPart1 int ,
	IDAudio INT,
	IDPicture INT,
	IDQUESTION INT,
	FOREIGN KEY (IDAudio) REFERENCES AUDIO(IDAudio),
	FOREIGN KEY (IDQUESTION) REFERENCES QUESTION(IDQUESTION),
	FOREIGN KEY (IDPicture) REFERENCES PICTURE(IDPicture)
);
go

CREATE TABLE Part2 (
	IDPart2 int primary key,
	PointPart2 int,
	IDAudio INT,
	IDPicture INT,
	IDQUESTION INT,
	FOREIGN KEY (IDAudio) REFERENCES AUDIO(IDAudio),
	FOREIGN KEY (IDQUESTION) REFERENCES QUESTION(IDQUESTION),
	FOREIGN KEY (IDPicture) REFERENCES PICTURE(IDPicture)
);
go

CREATE TABLE Part3 (
	IDPart3 int primary key,
	PointPart3 int,
	IDAudio INT,
	IDPicture INT,
	IDQUESTION INT,
	FOREIGN KEY (IDAudio) REFERENCES AUDIO(IDAudio),
	FOREIGN KEY (IDQUESTION) REFERENCES QUESTION(IDQUESTION),
	FOREIGN KEY (IDPicture) REFERENCES PICTURE(IDPicture)
);
go

CREATE TABLE Part4 (
	IDPart4 int primary key,
	PointPart4 int,
	IDAudio INT,
	IDPicture INT,
	IDQUESTION INT,
	FOREIGN KEY (IDAudio) REFERENCES AUDIO(IDAudio),
	FOREIGN KEY (IDQUESTION) REFERENCES QUESTION(IDQUESTION),
	FOREIGN KEY (IDPicture) REFERENCES PICTURE(IDPicture)
);
go

CREATE TABLE Part5 (
	IDPart5 int primary key,
	PointPart5 int,
	IDAudio INT,
	IDPicture INT,
	IDQUESTION INT,
	FOREIGN KEY (IDAudio) REFERENCES AUDIO(IDAudio),
	FOREIGN KEY (IDQUESTION) REFERENCES QUESTION(IDQUESTION),
	FOREIGN KEY (IDPicture) REFERENCES PICTURE(IDPicture)
);
go

CREATE TABLE Part6 (
	IDPart6 int primary key,
	PointPart6 int,
	IDAudio INT,
	IDPicture INT,
	IDQUESTION INT,
	FOREIGN KEY (IDAudio) REFERENCES AUDIO(IDAudio),
	FOREIGN KEY (IDQUESTION) REFERENCES QUESTION(IDQUESTION),
	FOREIGN KEY (IDPicture) REFERENCES PICTURE(IDPicture)
);
go

CREATE TABLE Part7 (
	IDPart7 int primary key,
	PointPart7 int,
	IDAudio INT,
	IDPicture INT,
	IDQUESTION INT,
	FOREIGN KEY (IDAudio) REFERENCES AUDIO(IDAudio),
	FOREIGN KEY (IDQUESTION) REFERENCES QUESTION(IDQUESTION),
	FOREIGN KEY (IDPicture) REFERENCES PICTURE(IDPicture)
);
go

CREATE TABLE QL_EXAM (
    IDPart1 INT,
	IDPart2 INT,
	IDPart3 INT,
	IDPart4 INT,
	IDPart5 INT,
	IDPart6 INT,
	IDPart7 INT,
    IDEXAM INT PRIMARY KEY,
	IDUser INT,
    FOREIGN KEY (IDPart1) REFERENCES Part1(IDPart1),
	FOREIGN KEY (IDPart2) REFERENCES Part2(IDPart2),
	FOREIGN KEY (IDPart3) REFERENCES Part3(IDPart3),
	FOREIGN KEY (IDPart4) REFERENCES Part4(IDPart4),
	FOREIGN KEY (IDPart5) REFERENCES Part5(IDPart5),
	FOREIGN KEY (IDPart6) REFERENCES Part6(IDPart6),
	FOREIGN KEY (IDPart7) REFERENCES Part7(IDPart7)
);
go

CREATE TABLE AUDIO (
	IDAudio INT PRIMARY KEY,
	LinkAudio TEXT NOT NULL
);
go

CREATE TABLE PICTURE (
	IDPicture INT PRIMARY KEY,
	LinkPicture TEXT NOT NULL
);
go
CREATE TABLE QUESTION (
	IDQUESTION INT PRIMARY KEY,
	LinkQUESTION TEXT NOT NULL,
	A TEXT NOT NULL,
	B TEXT NOT NULL,
	C TEXT NOT NULL,
	D TEXT NOT NULL,
	ANSWER TEXT NOT NULL
);
go

CREATE TABLE QL_DIEM (
	IDUser INT,
	IDEXAM INT,
	PointPart1 INT,
	PointPart2 INT,
	PointPart3 INT,
	PointPart4 INT,
	PointPart5 INT,
	PointPart6 INT,
	PointPart7 INT,
	TotalScore INT,
	FOREIGN KEY (IDUser) REFERENCES User1(IDUser),
	FOREIGN KEY (IDEXAM) REFERENCES EXAM(IDEXAM)
)
